server:
  port: 8086
spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://rahul-salve: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@github.com/rahul-salve/microservice_project.git
          clone-on-start: true
          refresh-rate: 30
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/