server:
  port: 8085

spring:
  config:
    import:
      - configserver:http://localhost:8086

  application:
    name: API-GATEWAY

  #eureka:
  #  instance:
  #  client:
  #   register-with-eureka: true
  #   serviceUrl:
  #     defaultZone: http://localhost:9090/eureka/
eureka:
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**

